# -*- coding: utf-8 -*-
"""1 лабораторная работа.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114Ey06-y0guXI68mtb1Woa8LRZWfk-lL
"""

print("Hellow world")

a = 7.5
b = 7.5
c = 7.5
x = (a**2 + b**2 - c**3)/2
print(x)#0

a = input()
b = input()
c = b*((a**3 + 14)/5)
print(c)#6

a = int(input())
b = int(input())
c = a**2 + b**2
print(c)#2

a = 15
b = 10
c = int(input())
x = int((a + b)/c)
print(x)#3

a = int(input())
b = int(input())
c = (a+b)**2
print(c)#4

a = int(input())
b = int(input())
c = int(input())
P = a + b + c
h = c**2-(b/2) ** 2
S = a * h / 2
print('P = ',P,'S = ',S)#5

a = int(input())
n = int(input())
c = int(a)
r = c // n
print(r)#7

a = int(input())
b = int(input())
d = a // b
u = a * b
o = a / b
print(d,'',u,'',o)#8

sec = int(input())
day = sec // 86400
hour = (sec - (day * 86400)) // 3600
min = (sec - (day * 86400 + hour * 3600)) // 60
s = sec - (day * 86400 + hour * 3600 + min * 60)
print (day,"",":",hour,"",":",min,"",":",s,"")

n = int(input())
print (n + n * 11 + n * 111)