# -*- coding: utf-8 -*-
"""3 лабораторная работа.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHG6uX40bYRbxDz3oxoW45y7hdSiKIgM
"""

months = ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"]
number = int(input("Введите номер месяца (от 1 до 12): "))
if 1 <= number <= 12:
    print(f"Месяц: {months[number - 1]}")
else:
    print("подумай ещё.")#1

число = int(input("Введите число: "))
if число % 2 == 0:
  print("Число чётное")
else:
  print("Число нечётное")#2

n = int(input("Введите число N: "))
if n > 40:
  print("stonks")
else:
  print("not stonks")#3

def is_year_leap(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    return False
year = int(input("Введите год: "))
print(is_year_leap(year))#4

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True
n = int(input("Введите число: "))
print(is_prime(n))#5

"""извините, не доделал 6,7 :("""

a = float(input("Введите значение a: "))
b = float(input("Введите значение b: "))
c = float(input("Введите значение c: "))
try:
  result = ((a ** 2 + b ** 3) / (c + 3)) / 4
  print(f"Результат неравенства: {result}")
  if result % 2 == 0:
              print("Результат чётный.")
  else:
              print("Результат нечётный.")
except ZeroDivisionError:
        print("Ошибка: деление на ноль")#Задание повышенной сложности